import jwt from 'jsonwebtoken';
import env from 'dotenv';

env.config();





const tokenAuthentication = (req, res, next) => {

  const token = req.body || req.query || req.headers['x-access-token'];

   // decode the token generated by user payload during signin or signup
   if(token){
     jwt.verify(token, SECRET_KEY, (err, decoded) =>{
       if(err){
         res.status(401);
         res.json({
           status:'Failed',
           message:'Authentication Failed. Tjen is either invalid or expired'
         })
       }else{
         req.decoded = decoded;
         next();
       }
     });
   }else{
     res.status(403);
     res.json({
      status:'Failed',
      message:'Invaled token. provide a correct token'
     });
   }
  };
  export default tokenAuthentication;